### ISSUE TITLE
light enhancement suggestion

### ISSUE THREAD

**Issue by gpolyn** [chenr2/AWS-SAM-Tutorial#3]
While perhaps familiar to AWS CloudFormation people, I was thrown by the gap between your [youtube walk-through](https://www.youtube.com/watch?v=xaCbIFH_d9k) at step 6, when you discuss the copy-pasting of _Swagger_ configuration from AWS API Gateway, and the final (pasted) code at line 24 of of `template.yaml` (58f5df958138aeb1eb68c4a63641113e52d2082a), which is different from what I found at my _Swagger_ configuration place. So, might it be useful to add a comment line above the entry explaining the use of dynamic vars?

**Comment by robcornerstone** [comment]
I probably won't get around to making changes to the commit history, but I can elaborate on this section of code in this comment here.

Line 24 in template.yaml:

```
!Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloLambda.Arn}/invocations
```

The `!Sub` [function](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html) lets you substitute variables into a literal string. Anything inside `${...}` gets interpreted by CloudFormation.

`${AWS::Region}` is a [pseudo parameter](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html) that gets translated into the current region (i.e. `us-east-1`). You might be used to seeing this as `!Ref "AWS::Region"`

And `${HelloLambda.Arn}` is the [GetAtt](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getatt.html) function (because of the dot syntax), and gives you the `Arn` of the Lambda. A more common form of the GetAtt function looks like this: `!GetAtt HelloLambda.Arn`

Hope this helps,
Robert

**Comment by gpolyn** [comment]
Thanks for the reply and for the repo, video.
